import './globals.css'
import {Inter} from 'next/font/google'
import {TheHeader} from "@/components/TheHeader";
import {TheFooter} from "@/components/TheFooter";
import styles from "./layout.module.css";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={styles.full_height + " " + inter.className}>
        <TheHeader/>
        <main className={styles.main}>
            {children}
        </main>
        <TheFooter/>
        </body>
        </html>
    )
}
